[manifest]
version = "1.0.0"
dump_lua = true
priority = 1

# Add mxms_modify_final_cashout
[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = '''
    dollars = dollars + G.GAME.interest_amount*math.min(math.floor(G.GAME.dollars/5), G.GAME.interest_cap/5)
end
'''
position = "after"
payload = '''

    for _, area in ipairs(SMODS.get_card_areas('jokers')) do
        for _, _card in ipairs(area.cards) do
            local obj = _card.config.center
            if obj.mxms_modify_final_cashout and type(obj.mxms_modify_final_cashout) == 'function' then
                local ret = obj:mxms_modify_final_cashout(_card, dollars)
            
                -- TARGET: mxms_modify_final_cashout per card
                if ret then
                    add_round_eval_row({dollars = ret, bonus = true, name='joker'..i, pitch = pitch, card = _card})
                    i = i+1
                    pitch = pitch + 0.06
                    dollars = dollars + ret
                end
            end
        end
    end
'''
match_indent = false