[manifest]
version = "1.0.0"
dump_lua = true
priority = 1

# Prevent unlock check while in menu

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = '''
if args.type == 'have_edition' then
'''
position = "at"
payload = '''
if args.type == 'have_edition' and G.STAGE == G.STAGES.RUN then
'''
match_indent = true
times = 1


# Fix copy_card causing crashes when trying to carry over a card stored in an ability table

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = '''
new_card.ability[k] = copy_table(v)
'''
position = "at"
payload = '''
if other.config.center.key:sub(1, 6) == "j_mxms" and other.ability[k].card then
    new_card.ability[k] = {card = nil, pos = nil}
else
    new_card.ability[k] = copy_table(v)
end
'''
match_indent = true
times = 1


# Secret Society show updated chip values on cards
[[patches]]
[patches.pattern]
target = 'functions/common_events.lua'
pattern = '''
if specific_vars.nominal_chips then
'''
position = '''after'''
payload = '''
    if next(SMODS.find_card('j_mxms_secret_society')) then
        specific_vars.nominal_chips = (Maximus.get_nominal_sum() - specific_vars.nominal_chips) * 2
    end
'''
match_indent = true
times = 1

# pre_reroll context
[[patches]]
[patches.pattern]
target = 'functions/button_callbacks.lua'
pattern = '''
calculate_reroll_cost(final_free)
'''
position = 'after'
payload = '''
SMODS.calculate_context({pre_reroll = true, cost = reroll_cost})
'''
match_indent = true
times = 1